In [2]:
import random

import pandas as pd

Verde = 1
Amarillo = 2
Cafe = 3
VerdeClaro = 4

Rojo = 1

Bajo =1 
Grueso = 2
Alto = 3
Corto = 4

NoTiene = 1
Pequeño = 2
Mediano =3
Grande = 4

# Definimos las categorías y sus valores numéricos

colores_hoja = [Verde, Amarillo, Cafe, VerdeClaro]

colores_fruto = [Rojo, Amarillo, Verde, Cafe]

tallos = [Bajo, Grueso, Alto, Corto]

tamanios_fruto = [NoTiene, Pequeño, Mediano, Grande]

 

# Crear una lista para almacenar los datos generados aleatoriamente

data = []

 

# Generar al menos 15 datos para cada categoría

for i in range(15):

    data.append([random.choice(colores_hoja),random.choice(colores_fruto),random.choice(tallos), random.choice(tamanios_fruto)])


# Crear un DataFrame a partir de los datos generados

df = pd.DataFrame(data, columns=["Color de la hoja", "Color del fruto", "Tallo", "Tamaño del fruto"])

 

# Mostrar el DataFrame

print(df)

# pd.set_option('display.max_rows', None)
# pd.reset_option('display.max_rows')

    Color de la hoja  Color del fruto  Tallo  Tamaño del fruto
0                  2                3      4                 1
1                  2                3      1                 3
2                  4                2      4                 3
3                  3                1      2                 3
4                  1                3      3                 3
5                  2                1      3                 2
6                  2                1      4                 1
7                  1                1      1                 2
8                  4                2      4                 4
9                  1                1      1                 1
10                 1                2      1                 3
11                 4                1      2                 1
12                 4                2      4                 1
13                 3                1      4                 4
14                 4                3      1           

In [3]:
df.to_csv('BASE_DATOS.csv', index = False)

In [4]:

import pandas as pd
import numpy as np

# Generar una matriz de 15x4 de números aleatorios entre 0 y 4
matrix = np.random.randint(1,5, size=(60, 4))

print(matrix)

[[2 3 1 2]
 [2 1 3 3]
 [4 1 4 4]
 [3 2 1 3]
 [4 3 2 3]
 [1 1 3 1]
 [2 1 3 2]
 [3 1 3 4]
 [3 4 3 4]
 [1 4 1 1]
 [3 1 1 1]
 [1 3 2 2]
 [2 3 2 1]
 [1 1 4 2]
 [3 2 2 4]
 [2 1 1 4]
 [4 3 2 4]
 [3 4 1 2]
 [2 2 1 3]
 [1 1 2 3]
 [1 1 4 4]
 [3 3 2 4]
 [3 3 2 1]
 [4 3 4 3]
 [2 4 4 4]
 [1 3 3 2]
 [3 2 1 3]
 [1 4 3 1]
 [2 3 2 4]
 [1 2 4 3]
 [1 4 1 1]
 [3 4 4 3]
 [4 3 1 3]
 [4 4 3 2]
 [1 4 2 1]
 [2 1 1 1]
 [2 2 1 4]
 [4 2 3 2]
 [2 3 4 3]
 [4 1 1 4]
 [2 4 3 1]
 [1 3 3 4]
 [4 1 2 4]
 [2 2 1 1]
 [3 3 4 4]
 [1 2 3 1]
 [1 4 1 1]
 [3 4 2 2]
 [4 3 3 2]
 [2 2 3 3]
 [4 1 2 1]
 [3 1 2 4]
 [2 2 4 1]
 [4 4 4 4]
 [2 4 4 4]
 [3 2 4 4]
 [3 2 2 4]
 [1 3 2 2]
 [1 4 1 3]
 [2 4 3 3]]


In [5]:
matriz1 = pd.DataFrame(matrix, columns=['Color', 'Contextura', 'Aromas', 'Barril de añejamiento'])

print(matriz1) 

# matriz1.to_excel('holacsv.xlsx', index = False)

    colores_hoja  colores_fruto  tallos  tamanios_fruto
0              2              3       1               2
1              2              1       3               3
2              4              1       4               4
3              3              2       1               3
4              4              3       2               3
5              1              1       3               1
6              2              1       3               2
7              3              1       3               4
8              3              4       3               4
9              1              4       1               1
10             3              1       1               1
11             1              3       2               2
12             2              3       2               1
13             1              1       4               2
14             3              2       2               4
15             2              1       1               4
16             4              3       2         